name: den
version: 0.1.0
author: Sean Eagan <seaneagan1@gmail.com>
description: Den is a place for doing pub-related things, like updating your pubspec, from within the comfort and convenience of your own home (if your home is the command line).
homepage: https://github.com/seaneagan/den
dependencies:
  ansicolor: any
  contrast: '>=0.1.1 <0.2.0'
  path: '>=1.3.0 <2.0.0'
  pub_package_data: any
  pub_semver: '>=1.0.0 <2.0.0'
  quiver: '>=0.18.2'
  source_span: any
  unscripted: '>=0.4.3 <0.5.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <12.0.0'
executables:
  den: null
