name: den
version: 0.0.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Interact with pubspecs.
homepage: https://github.com/seaneagan/den
dependencies:
  ansicolor: any
  path: '>=1.3.0 <2.0.0'
  pub_package_data: any
  pub_semver: '>=1.0.0 <2.0.0'
  source_span: any
  unscripted: '>=0.4.3 <0.5.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <12.0.0'
executables:
  den: null
