name: den
version: 0.2.0
author: Sean Eagan <seaneagan1@gmail.com>
description: A pubspec authoring tool.
homepage: https://github.com/seaneagan/den
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  ansicolor: any
  contrast: '>=0.1.1 <0.2.0'
  den_api:
    git: https://github.com/Pacane/den_api
  path: "^1.4.2"
  prompt: '>=0.1.7 <0.2.0'
  pub_package_data: any
  pub_semver: '>=1.1.0 <2.0.0'
  quiver: '>=0.20.0 <0.26.0'
  source_span: any
  unscripted: "^0.6.2"
  which: '>=0.1.3 <0.2.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  test: "^0.12.24+8"
executables:
  den: null
